# -*- coding: utf-8 -*-
"""cricket.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vevFI-eXedkKKAdKHXHUFqQw8JlclEhR
"""

import matplotlib.pyplot as plt

players = ['Virat', 'Rohit', 'Amla', 'ABD', 'Taylor', 'Sanga', 'Dilshan', 'Morgan', 'Kane', 'Guptill']
batting_avg = [60.79, 53.56, 49.76, 64.20, 54.01, 52.96, 44.65, 40.52, 47.90, 42.35]
batting_Sr = [94.11, 90.63, 89.11, 109.76, 83.56, 84.7, 87.03, 94.9, 81.82, 88.06]

plt.figure(figsize=(8,4))
plt.scatter(batting_avg, batting_Sr, color='black', s=100)
for i, player in enumerate(players):
    plt.text(batting_avg[i], batting_Sr[i], player, fontsize=10, ha='right')

plt.title('2010s top scorer Avg vs SR')
plt.xlabel('Batting Average')
plt.ylabel('Batting Sr')
plt.grid(True)
plt.show()